# Generated by Django 5.0.6 on 2026-08-15 03:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(default='Academic', max_length=60)),
                ('awarded_by', models.CharField(blank=True, max_length=120)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('description', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='academics.student')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COMPLAINT', 'Complaint'), ('SUGGESTION', 'Suggestion')], default='COMPLAINT', max_length=10)),
                ('report_to', models.CharField(choices=[('VC', 'Vice-Chancellor'), ('REGISTRAR', 'Registrar'), ('PROCTOR', 'Proctor'), ('LIBRARIAN', 'Librarian'), ('ACCOUNTS', 'Accounts Officer'), ('ICT', 'ICT Cell')], default='PROCTOR', max_length=10)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ROUTED', 'Routed'), ('IN_REVIEW', 'In review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=10)),
                ('response', models.TextField(blank=True)),
                ('tracking_code', models.CharField(max_length=14, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, help_text='Left empty when submitted anonymously.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='academics.student')),
            ],
            options={
                'verbose_name': 'complaint / suggestion',
                'verbose_name_plural': 'complaints & suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('SEMINAR', 'Seminar'), ('WORKSHOP', 'Workshop'), ('MEETING', 'Faculty meeting'), ('CULTURAL', 'Cultural programme')], default='SEMINAR', max_length=10)),
                ('venue', models.CharField(max_length=120)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='academics.teacher')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamRemuneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=120)),
                ('particulars', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remunerations', to='academics.teacher')),
            ],
            options={
                'verbose_name': 'exam remuneration',
                'ordering': ['-bill_date'],
            },
        ),
        migrations.CreateModel(
            name='HouseAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_category', models.CharField(choices=[('A', 'Category A - Professor'), ('B', 'Category B - Associate Professor'), ('C', 'Category C - Assistant Professor'), ('D', 'Category D - Lecturer / Officer')], default='D', max_length=1)),
                ('preferred_quarter', models.CharField(blank=True, max_length=80)),
                ('family_members', models.PositiveSmallIntegerField(default=1)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_requests', to='academics.teacher')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual leave'), ('EARNED', 'Earned leave'), ('MEDICAL', 'Medical leave'), ('STUDY', 'Study leave'), ('MATERNITY', 'Maternity leave')], default='CASUAL', max_length=10)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('address_during_leave', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='academics.teacher')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('UNIVERSITY', 'University'), ('DEPARTMENT', 'Department'), ('EXAM', 'Examination'), ('ACCOUNTS', 'Accounts'), ('EVENT', 'Event')], default='UNIVERSITY', max_length=12)),
                ('audience', models.CharField(choices=[('ALL', 'Everyone'), ('STUDENT', 'Students'), ('TEACHER', 'Teachers'), ('ADMIN', 'Administration')], default='ALL', max_length=8)),
                ('body', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('post_date', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-post_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PostgraduateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('MS', 'M.S.'), ('MBA', 'MBA'), ('PHD', 'PhD')], default='MS', max_length=4)),
                ('research_title', models.CharField(max_length=220)),
                ('synopsis', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('thesis_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_applications', to='academics.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_applications', to='academics.teacher')),
            ],
            options={
                'verbose_name': 'postgraduate application',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('authors', models.CharField(blank=True, max_length=250)),
                ('journal_name', models.CharField(blank=True, max_length=180)),
                ('kind', models.CharField(choices=[('JOURNAL', 'Journal article'), ('CONFERENCE', 'Conference paper'), ('BOOK', 'Book / chapter')], default='JOURNAL', max_length=10)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('indexing', models.CharField(blank=True, help_text='Scopus, SCIE, etc.', max_length=60)),
                ('doi_link', models.URLField(blank=True)),
                ('in_baures', models.BooleanField(default=False, verbose_name='listed in BAURES repository')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='academics.teacher')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Research news', max_length=60)),
                ('body', models.TextField()),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_posts', to='academics.teacher')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('MICROBUS', 'Microbus'), ('CAR', 'Car'), ('BUS', 'Bus'), ('AMBULANCE', 'Ambulance')], default='MICROBUS', max_length=10)),
                ('purpose', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=120)),
                ('journey_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('passengers', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_requests', to='academics.teacher')),
            ],
            options={
                'verbose_name': 'vehicle requisition',
                'ordering': ['-journey_date'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=120)),
                ('menu_order', models.PositiveSmallIntegerField(default=1)),
                ('external_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft')], default='PUBLISHED', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Rich-text page body.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='portal.websitemenu', verbose_name='parent menu')),
            ],
            options={
                'verbose_name': 'website menu',
                'ordering': ['menu_order', 'page_title'],
            },
        ),
        migrations.CreateModel(
            name='CourseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.PositiveSmallIntegerField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(3, 'Always'), (2, 'Mostly'), (1, 'Seldom'), (0, 'Never')], default=3)),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='academics.enrollment')),
            ],
            options={
                'verbose_name': 'course feedback',
                'verbose_name_plural': 'course feedback',
                'ordering': ['question_no'],
                'unique_together': {('enrollment', 'question_no')},
            },
        ),
    ]
