# Generated by Django 5.0.6 on 2026-08-15 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_enrollmentdeadline_notice'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='portal.notice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_dismissals', to='academics.student')),
            ],
            options={
                'verbose_name': 'notice dismissal',
                'ordering': ['-dismissed_at'],
                'unique_together': {('student', 'notice')},
            },
        ),
    ]
