# Generated by Django 5.0.6 on 2026-08-15 03:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail address')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Course Teacher'), ('ADMIN', 'Admin / Registrar')], default='STUDENT', max_length=12)),
                ('designation', models.CharField(blank=True, choices=[('REGISTRAR', 'Registrar / Academic Admin'), ('EXAM_CONTROLLER', 'Controller of Examinations'), ('ACCOUNTS', 'Accounts Officer'), ('PROCTOR', 'Proctor / Student Affairs Adviser'), ('ICT', 'ICT Cell / System Admin'), ('VC', 'Vice-Chancellor / Pro-VC')], help_text='Only for administrative staff.', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user account',
                'verbose_name_plural': 'user accounts',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccessPasskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Exactly 6 digits. Share it with the user through an approved channel.', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'The passkey must be exactly 6 digits.')], verbose_name='6-digit passkey')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave empty for a passkey that never expires.', null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('locked_until', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passkey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'access passkey',
                'verbose_name_plural': 'access passkeys',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GATE_PASS', 'Gate cleared'), ('GATE_FAIL', 'Gate rejected'), ('LOGOUT', 'Signed out'), ('CREATE', 'Record created'), ('UPDATE', 'Record updated'), ('APPROVE', 'Request approved'), ('REJECT', 'Request rejected'), ('PUBLISH', 'Content published')], max_length=16)),
                ('entity', models.CharField(blank=True, max_length=80)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit trail',
                'ordering': ['-created_at'],
            },
        ),
    ]
