# Generated by Django 5.0.6 on 2026-08-15 03:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=12, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('COMPULSORY', 'Compulsory'), ('OPTIONAL', 'Optional'), ('ELECTIVE', 'Elective')], default='COMPULSORY', max_length=12)),
                ('course_type', models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical / Lab'), ('THESIS', 'Thesis / Project')], default='THEORY', max_length=10)),
                ('credit', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('contact_hour', models.PositiveSmallIntegerField(default=3)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('faculty_name', models.CharField(max_length=120)),
                ('established_year', models.PositiveIntegerField(default=2018)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(help_text='e.g. Semester Final, Spring 2026', max_length=120)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('late_end_date', models.DateField(blank=True, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=3500, max_digits=8)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('is_open', models.BooleanField(default=True)),
                ('memo_no', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'enrollment deadline',
                'ordering': ['-year', 'level', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(choices=[('LECTURER', 'Lecturer'), ('ASSISTANT', 'Assistant Professor'), ('ASSOCIATE', 'Associate Professor'), ('PROFESSOR', 'Professor')], default='LECTURER', max_length=12)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('contact_no', models.CharField(blank=True, max_length=20)),
                ('office_room', models.CharField(blank=True, max_length=60)),
                ('specialization', models.CharField(blank=True, max_length=160)),
                ('photo_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('section', models.CharField(default='A', max_length=4)),
                ('seat_capacity', models.PositiveSmallIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='academics.course')),
            ],
            options={
                'ordering': ['-year', 'level', 'semester', 'course__course_code'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=40)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.courseoffer')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ENROLLED', max_length=10)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.courseoffer')),
            ],
            options={
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=24, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('signed_by', models.CharField(default='Controller of Examinations, JSTU', max_length=120)),
                ('is_released', models.BooleanField(default=False)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='academics.enrollmentdeadline')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(default='Semester Final', max_length=120)),
                ('exam_type', models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical')], default='THEORY', max_length=10)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=180)),
                ('exam_place', models.CharField(max_length=120)),
                ('memo_no', models.CharField(blank=True, max_length=40)),
                ('is_published', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academics.courseoffer')),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='FormFillup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=24, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=3500, max_digits=8)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='UNPAID', max_length=8)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending semester'), ('ACCOUNTS', 'Accounts seen pending'), ('APPROVED', 'Approved semester'), ('FINAL', 'Final approval'), ('HELD', 'Held'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('is_late', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_fillups', to='academics.enrollmentdeadline')),
            ],
            options={
                'verbose_name': 'form fill-up',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('method', models.CharField(choices=[('JANATA', 'Janata Bank Gateway'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('COUNTER', 'Bank counter')], default='JANATA', max_length=8)),
                ('transaction_id', models.CharField(blank=True, max_length=40)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=8)),
                ('form_fillup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.formfillup')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ct_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('repeat_final_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=3)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.enrollment')),
            ],
            options={
                'verbose_name_plural': 'marks',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('degree_level', models.CharField(choices=[('BSC', 'Bachelor'), ('MS', 'M.S. / MBA'), ('PHD', 'PhD')], default='BSC', max_length=4)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.department')),
            ],
            options={
                'ordering': ['department__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('registration_no', models.CharField(max_length=25, unique=True)),
                ('session', models.CharField(help_text='e.g. 2024-25', max_length=12)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('batch_year', models.PositiveIntegerField(default=2024)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('contact_no', models.CharField(blank=True, max_length=20)),
                ('present_address', models.CharField(blank=True, max_length=200)),
                ('permanent_address', models.CharField(blank=True, max_length=200)),
                ('photo_url', models.URLField(blank=True)),
                ('guardian_name', models.CharField(blank=True, max_length=120)),
                ('guardian_relation', models.CharField(blank=True, max_length=40)),
                ('guardian_contact', models.CharField(blank=True, max_length=20)),
                ('guardian_occupation', models.CharField(blank=True, max_length=80)),
                ('bank_name', models.CharField(blank=True, max_length=80)),
                ('bank_branch', models.CharField(blank=True, max_length=80)),
                ('bank_account_no', models.CharField(blank=True, max_length=30)),
                ('university_email', models.EmailField(blank=True, max_length=254)),
                ('internet_username', models.CharField(blank=True, max_length=40)),
                ('internet_active', models.BooleanField(default=True)),
                ('data_quota_gb', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRADUATED', 'Graduated'), ('DROPPED', 'Dropped out'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=10)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.program')),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
    ]
