# Generated by Django 5.0.6 on 2026-08-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_enrollmentdeadline_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=120, verbose_name="father's name"),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name_bn',
            field=models.CharField(blank=True, max_length=120, verbose_name="father's name (Bangla)"),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=120, verbose_name="mother's name"),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name_bn',
            field=models.CharField(blank=True, max_length=120, verbose_name="mother's name (Bangla)"),
        ),
        migrations.AddField(
            model_name='student',
            name='name_bn',
            field=models.CharField(blank=True, max_length=120, verbose_name='name (Bangla)'),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('ISLAM', 'Islam'), ('HINDU', 'Hindu / Shonaton'), ('CHRISTIAN', 'Christian'), ('BUDDHIST', 'Buddhist'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
