# Generated by Django 5.0.6 on 2026-08-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_student_personal_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('ISLAM', 'Islam'), ('HINDU', 'Hindu'), ('CHRISTIAN', 'Christian'), ('BUDDHIST', 'Buddhist'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
