# Generated by Django 5.0.6 on 2026-08-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_religion_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfillup',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='form_fillups', to='academics.courseoffer'),
        ),
        migrations.AddField(
            model_name='formfillup',
            name='is_submitted',
            field=models.BooleanField(default=False, help_text='Marked done; awaiting payment.'),
        ),
        migrations.AddField(
            model_name='formfillup',
            name='signed',
            field=models.BooleanField(default=False, help_text='Student attached their signature.'),
        ),
        migrations.AddField(
            model_name='student',
            name='signature',
            field=models.ImageField(blank=True, help_text='Scanned signature used on exam forms.', null=True, upload_to='signatures/'),
        ),
    ]
