# Generated by Django 5.0.6 on 2026-08-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_exam_form_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfillup',
            name='examinee_type',
            field=models.CharField(blank=True, choices=[('REGULAR', 'নিয়মিত'), ('IRREGULAR', 'অনিয়মিত'), ('IMPROVEMENT', 'মান উন্নয়ন')], help_text='Ticked on the examination form.', max_length=12),
        ),
    ]
