# Generated by Django 5.0.6 on 2026-08-23 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_examinee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='receipt',
            field=models.FileField(blank=True, help_text='Bank payment slip uploaded by the student.', null=True, upload_to='receipts/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='remarks',
            field=models.CharField(blank=True, help_text='Why the Accounts Office rejected the slip.', max_length=200),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
